name: Build AX88178 Driver

on:
  push:
 

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout the repository
      uses: actions/checkout@v2

    - name: Set up build environment
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential
        sudo apt-get install -y gcc-arm-linux-gnueabi

    - name: Clone AX88178 repository
      run: |
        git clone --depth=1 https://github.com/scratchyes/AX88178.git
        cd AX88178

    - name: Apply patch for MSM8916
      run: |
        wget https://example.com/msm8916.patch
        patch -p1 < msm8916.patch

    - name: Build driver module
      run: |
        make ARCH=arm64 modules

    - name: Archive driver artifact
      run: |
        tar cvfz driver_artifact.tar.gz *.ko

    - name: Upload driver artifact
      uses: actions/upload-artifact@v2
      with:
        name: driver
        path: AX88178/driver_artifact.tar.gz
