name: Build AX88178 Driver

on:
  push:
 

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout the repository
      uses: actions/checkout@v2

    - name: Set up build environment
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential
        sudo apt-get install -y gcc-arm-linux-gnueabi

    - name: Clone AX88178 repository
      run: |
        git clone --depth=1 https://github.com/scratchyes/AX88178.git
        cd AX88178

   - name: Build driver module
      run: |
        cd AX88178
        make ARCH=arm64 CROSS_COMPILE=aarch64-linux-gnu- modules
        
    - name: Archive driver artifact
      run: |
        tar czvf driver.tar.gz AX88178/ax88179_178a.ko

    - name: Upload driver artifact
      uses: actions/upload-artifact@v2
      with:
        name: driver
        path: driver.tar.gz
