name: Build AX88178 Driver
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential
      - name: Clone AX88178 repository
      run: |
        git clone --depth=1 https://github.com/scratchyes/AX88178.git
        cd AX88178

      - name: Compile AX88178 Driver
        run: |
          cd AX88178
          make ARCH=arm64 CROSS_COMPILE=arm-none-linux-gnueabi- modules

      - name: Capture Compiled File
        run: |
          cp AX88178/ax88179_178a.ko ${{ github.workspace }}/ax88179_178a.ko
