name: AX88178 Driver

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        platform: [arm64]

    steps:
    - name: Set up Node.js 16.x
      uses: actions/setup-node@v2
      with:
        node-version: 16

    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt install build-essential
        sudo apt install linux-headers-$(uname -r)
    - name: Clone AX88178 repository
      run: |
          git clone --depth=1 https://github.com/scratchyes/AX88178.git AX88178

    - name: Compile AX88178 driver
      run: |
        cd AX88178
        ls 
        make clean
        make -C /lib/modules/$(uname -r)/build M=$PWD modules
        ls

    - name: Copy module to output directory
      run: cp AX88178/ax88179_178a.ko ${{ github.workspace }}/ax88179_178a.ko

    - name: Upload module artifact
      uses: actions/upload-artifact@v2
      with:
        name: ax88178-driver
        path: ${{ github.workspace }}/ax88179_178a.ko
